### PR TITLE
Create when-to-hire-a-full-team-of-engineers.md

### PR DESCRIPTION
**Pull request by snabahani**
@CBS2015 @KHourigan @reillyko

### CODE REVIEW

**Comment by reillyko** [comment]
Agree with Sarah S - look at the image link again; it does not seem to display.  I had that issue also, did a google image search and the link was too long so it did not display.  Try clicking the "View Image" button and then use that link.

Potential additions to content:

Entrepreneurs should consider a Concierge, Wizard of Oz, or Email-only startup in the beginning. The first thing you want to do is optimize for learning, not building.  Work with your customers to figure out their needs. You don't always need to build for scale early.

**Comment by reillyko** [comment]
:+1:

**Comment by snabahani** [comment]
@reillyko @KHourigan @CBS2015

**Comment by CBS2015** [comment]
:+1:

**Pull request merged**
